### PR TITLE
Fix plot_pd function to work with matplotlib 3.8.0 changes

### LINKED ISSUE #964: PDP plots failing with `matplotlib==3.8.0`
E.g.

```python
# plot partial dependece curves
plot_pd(exp=exp,
        n_cols=3,
        sharey='row',
        fig_kw={'figheight': 10, 'figwidth': 15});
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 2
      1 # plot partial dependece curves
----> 2 plot_pd(exp=exp,
      3         n_cols=3,
      4         sharey='row',
      5         fig_kw={'figheight': 10, 'figwidth': 15});

File ~/PycharmProjects/public-fork-alibi/alibi/explainers/partial_dependence.py:1099, in plot_pd(exp, features, target, n_cols, n_ice, center, pd_limits, levels, ax, sharey, pd_num_kw, ice_num_kw, pd_cat_kw, ice_cat_kw, pd_num_num_kw, pd_num_cat_kw, pd_cat_cat_kw, fig_kw)
   1097     min_val = min([ax_pd_lim[0] for _, ax_pd_lim in ax_group])
   1098     max_val = max([ax_pd_lim[1] for _, ax_pd_lim in ax_group])
-> 1099     ax_group[0][0].get_shared_y_axes().join(ax_group[0][0], *[ax[0] for ax in ax_group[1:]])
   1100     ax_group[0][0].set_ylim(min_val, max_val)
   1102 fig.set(**fig_kw)

AttributeError: 'GrouperView' object has no attribute 'join'
```

### PR DESCRIPTION
**Pull request by jklaise**
Closes #964.

Have checked that the output plots on the `pdp_regression_bike.ipynb` notebook are the same.

### CODE REVIEW

File: alibi/explainers/partial_dependence.py [hunk 1]
```diff
@@ -1096,8 +1096,10 @@ def _is_categorical(feature):
     for ax_group in one_way_axs.values():
         min_val = min([ax_pd_lim[0] for _, ax_pd_lim in ax_group])
         max_val = max([ax_pd_lim[1] for _, ax_pd_lim in ax_group])
-        ax_group[0][0].get_shared_y_axes().join(ax_group[0][0], *[ax[0] for ax in ax_group[1:]])
-        ax_group[0][0].set_ylim(min_val, max_val)
+        axs = [ax[0] for ax in ax_group]
+        for ax1, ax2 in zip(axs, axs[1:]):
```
[the remark this answers is not in the document]
Comment (jklaise) [reply alibi/explainers/partial_dependence.py]: Good point, I've changed to your suggestion and tested that it works the same, the code is slightly nicer!

**Review by RobertSamoilescu — APPROVED** [review]
LGTM!
