### ISSUE TITLE
Integrated Gradients notebook - np.ndarray kwargs but tf.Tensor expected

### ISSUE THREAD

**Issue by RobertSamoilescu** [SeldonIO/alibi#527]
The latest versions of `transformers` are expecting the `kwargs`  to be `Union[np.ndarray, tf.Tensors]` but work only with `tf.Tensor`. Thus, passing, for example, the attention map as `np.ndarray` (as they are currently passed in the notebook examples) will fail the casting of the tensor shape to a list:
```
-> 1831     static = tensor.shape.as_list()
   1832 
   1833     return [dynamic[i] if s is None else s for i, s in enumerate(static)]

AttributeError: 'tuple' object has no attribute 'as_list'
```

Note that the notebook was working with the `4.6.1` version of `transformers`, but currently `alibi` requires `>=4.7.0` introduced for the AnchorText with Language models #432)

The current notebook example will fail for in the following function:
```python
def get_embeddings(X_train, model, batch_size=50):
    from tqdm import tqdm
    
    args = X_train['input_ids']
    kwargs = {k:v for k, v in  X_train.items() if k != 'input_ids'}
    
    dataset = tf.data.Dataset.from_tensor_slices((args, kwargs)).batch(batch_size)
    dataset = dataset.as_numpy_iterator()
    
    embbedings = []
    for X_batch in tqdm(dataset):
        args_b, kwargs_b = X_batch
        batch_embeddings = model(args_b, **kwargs_b)
        embbedings.append(batch_embeddings.last_hidden_state.numpy())

    return np.concatenate(embbedings, axis=0)
```
when calling `model(args_b, **kwargs_b)`.

Previous calls to model explain will pass since the `kwargs` are not considered for the explanations (see issue #524 ).

For PR #525 the same issue will arise even before when calling the explain method.

**Comment by RobertSamoilescu** [comment]
[huggingface/transformers#14404](https://github.com/huggingface/transformers/issues/14404)

**Comment by jklaise** [comment]
Fixed by #528 .
